### ISSUE TITLE
Missing example for Subscriber Update SOAP request

### ISSUE THREAD

**Issue by MrGrabazu** [salesforce-marketingcloud/postman#10]
Hi, 
This project is great, it helps me a lot.
I have hard time to find out how to make an update request through SOAP API to update subscriber. And sadly your collection doesn't include this request.
Do you planned to add it soon ?

Thank you :)

**Comment by acates1982** [comment]
@MrGrabazu that's a good request for an addition. I will add it to the list of items to add. We have the create and retrieve examples but I didn't include an update. Given the public workspace collaboration functionality of Postman, if you would like to make the addition and issue a pull request I can work on merging it in. Documentation for collaboration can be found here: https://github.com/salesforce-marketingcloud/postman/blob/master/contributing.md
