### ISSUE TITLE
ERROR: getaddrinfo ENOTFOUND .auth.marketingcloudapis.com

### ISSUE THREAD

**Issue by AlexZero-0** [salesforce-marketingcloud/postman#11]
Hello,

Nice project, very helpful. I would like to use it but if I try to make any kind of API Call I receive this error:

![image](https://user-images.githubusercontent.com/85925543/122007712-e8517700-cdc0-11eb-86b8-a1f363216724.png)

I've followed the instruction and after I downloaded the collection I've added the variables, but none of them seems to work. 
Some help please?

**Comment by eliotharper** [comment]
@AlexZero-0 can you confirm that you've [selected the correct enviromment](https://learning.postman.com/docs/sending-requests/managing-environments/#selecting-an-active-environment) (which contains your environment variables)?

**Comment by AlexZero-0** [comment]
@eliotharper I don't have an environment set up, only the collection (I've followed the instructions in [here](https://github.com/salesforce-marketingcloud/postman/blob/master/install-the-collection.md)). But I figured out, I added the values only under initial value and not under current value as well (new to Postman).

It works for now. Thank you!

**Comment by acates1982** [comment]
Sorry for the delay in response @AlexZero-0! This is a common issue I've been seeing. I will make an adjustment to the documentation to be sure to indicate placement of the values under the "Current Value" of the collection. Thanks @eliotharper for helping as well!
